package BankingApp;


/**
* BankingApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Friday, 22 May 2026 19:49:35 o'clock IST
*/

public interface AccountOperations 
{
  double getBalance (String accNo);
  void deposit (String accNo, double amount);
  void withdraw (String accNo, double amount) throws BankingApp.InsufficientBalance;
} // interface AccountOperations
