package BankingApp;

/**
* BankingApp/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Friday, 22 May 2026 19:49:35 o'clock IST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public BankingApp.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (BankingApp.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankingApp.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankingApp.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankingApp.AccountHelper.type ();
  }

}
