package BankingApp;


/**
* BankingApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Friday, 22 May 2026 19:49:35 o'clock IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
