package BankingApp;

/**
* BankingApp/InsufficientBalanceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Friday, 22 May 2026 19:49:35 o'clock IST
*/

public final class InsufficientBalanceHolder implements org.omg.CORBA.portable.Streamable
{
  public BankingApp.InsufficientBalance value = null;

  public InsufficientBalanceHolder ()
  {
  }

  public InsufficientBalanceHolder (BankingApp.InsufficientBalance initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankingApp.InsufficientBalanceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankingApp.InsufficientBalanceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankingApp.InsufficientBalanceHelper.type ();
  }

}
